[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "wssecurityjava"
description = "A Salesforce Function showcasing WSS4J Library"
type = "function"
salesforce-api-version = "53.0"
